#Gradle
org.gradle.jvmargs=-Xmx8192M -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1G
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true

#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M
kotlin.incremental=true
kotlin.incremental.usePreciseJavaTracking=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.native.ignoreDisabledTargets=true
android.cacheCompileLibResources=true


kotlin.native.disableCompilerDaemon = true