# global configuration, name will show on github actions
name: KMP CI/CD

env:
  APK_PATH: androidApp/build/outputs/apk/release/androidApp-release.apk

# run this workflow when I push to any branch
on:
  push:
    branches:
      - '**'

jobs:
  # --- STAGE: COMPILE ---
  compile-android:
    name: "Compile Android"
    runs-on: ubuntu-latest  # run the following steps on a linux machine

    steps:
      # clone from repo to runner
      - uses: actions/checkout@v4

      # gradlew executable permissions
      - name: Make gradlew executable
        run: chmod +x gradlew # change mode chmod): (+)add (x)exectuable target-file:gradlew

      # install JDK 17
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # optimise gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # compile the APK
      - name: Build Android Release APK
        run: ./gradlew :androidApp:assembleRelease

      # save the apk to repo
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: ${{ env.APK_PATH }}

  compile-ios:
    name: "Compile: iOS (Verification)"
    runs-on: macos-latest # run the following steps on a mac
    steps:
      # clone from repo to runner
      - uses: actions/checkout@v4

      # gradlew executable permissions
      - name: Make gradlew executable
        run: chmod +x gradlew

      # install java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # optimise gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # test that iOS version compiles (currently not building)
      - name: Verify Shared Compilation for iOS
        run: ./gradlew :shared:compileKotlinIosSimulatorArm64

  # --- STAGE: TEST ---
  test:
    name: "Test: Unit Tests"
    # needs: [compile-android, compile-ios] # don't run if either version doesn't build
    runs-on: ubuntu-latest  # run the following steps on linux
    steps:

      # clone repo
      - uses: actions/checkout@v4

      # gradlew executable permissions
      - name: Make gradlew executable
        run: chmod +x gradlew

      # install Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # optimise gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # run the tests in shared/src/commonTest
      # run the tests in shared/src/androidHostTest
      - name: Run Common & Android Tests
        run: ./gradlew :shared:testAndroidHostTest

  # --- STAGE: DEPLOY ---
  deploy-android:
    name: "Deploy via Firebase"
    needs: [test, compile-android] # do not run if test does not run successfully
    if: github.ref == 'refs/heads/main' # only deploy if on main
    runs-on: ubuntu-latest # run the steps on linux

    steps:
      # clone repo
      - uses: actions/checkout@v4

      # download apk from the repo
      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-release-apk
          path: androidApp/build/outputs/apk/release/

      # Authenticate using the Service Account
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      # Run Firebase CLI via npx
      - name: Distribute to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        run: |
          npx firebase-tools appdistribution:distribute "${{ env.APK_PATH }}" \
            --app "${{ secrets.FIREBASE_ANDROID_APP_ID }}" \
            --groups internal-dev \
            --release-notes "New build from GitHub Actions"
